import React, { useState } from 'react';
import DashboardLayout from '../components/layout/DashboardLayout';
import { UserRole } from '../types';
import { MANAGEMENT_MENU, ATTENDANCE_DATA } from '../constants';
import StatCard from '../components/ui/StatCard';
import Card from '../components/ui/Card';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { getAIAnalysis } from '../services/geminiService';
import Button from '../components/ui/Button';
import Financials from '../components/management/Financials';
import Admissions from '../components/management/Admissions';
import Staffing from '../components/management/Staffing';
import AIPerformanceInsights from '../components/management/AIPerformanceInsights';
import AIFinancialForecasting from '../components/management/AIFinancialForecasting';
import AIStaffEfficiencyEvaluator from '../components/management/AIStaffEfficiencyEvaluator';
import AIStudentSuccessPredictor from '../components/management/AIStudentSuccessPredictor';
import AIDecisionSupportSystem from '../components/management/AIDecisionSupportSystem';
import AIReportSummarizer from '../components/management/AIReportSummarizer';
import AIBudgetOptimizer from '../components/management/AIBudgetOptimizer';
import PlaceholderContent from '../components/ui/PlaceholderContent';

const ManagementDashboard: React.FC<{ setUserRole: (role: UserRole | null) => void }> = ({ setUserRole }) => {
    const [activeView, setActiveView] = useState('dashboard');
    const [deptPerformance, setDeptPerformance] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    const handleLogout = () => {
        setUserRole(null);
    };
    
    const fetchDeptPerformance = async () => {
        setIsLoading(true);
        const prompt = `Summarize the performance of different academic departments based on this data:
        - Science: Avg Grade 82%, Attendance 91%, 3 new publications.
        - Arts: Avg Grade 78%, Attendance 88%, 5 student awards.
        - Commerce: Avg Grade 85%, Attendance 94%, 95% placement rate.
        - Engineering: Avg Grade 75%, Attendance 85%, 1 research grant secured.
        Provide a concise summary for management, highlighting strengths and areas needing attention.`;
        const result = await getAIAnalysis(prompt);
        setDeptPerformance(result);
        setIsLoading(false);
    };

    const renderContent = () => {
        switch (activeView) {
            case 'aiDeptPerformance':
                 return (
                    <Card title="AI Department-wise Performance Analysis" icon="fa-solid fa-sitemap">
                        <p className="mb-4 text-gray-600">Get a high-level summary of departmental performance, generated by AI, to aid in strategic decision-making.</p>
                        <Button onClick={fetchDeptPerformance} isLoading={isLoading}>
                            <i className="fa-solid fa-magnifying-glass-chart mr-2"></i> Generate Analysis
                        </Button>
                        {isLoading && <p className="mt-4 text-primary">AI is compiling reports... Please wait.</p>}
                        {deptPerformance && (
                            <div className="mt-6 bg-gray-50 p-4 rounded-md">
                                <h4 className="font-semibold text-lg mb-2">AI Summary:</h4>
                                <pre className="whitespace-pre-wrap font-sans text-sm text-gray-800">{deptPerformance}</pre>
                            </div>
                        )}
                    </Card>
                );
            case 'financials':
                return <Financials />;
            case 'admissions':
                return <Admissions />;
            case 'staffing':
                return <Staffing />;
            case 'aiPerformanceInsights':
                return <AIPerformanceInsights />;
            case 'aiFinancialForecasting':
                return <AIFinancialForecasting />;
            case 'aiStaffEfficiency':
                return <AIStaffEfficiencyEvaluator />;
            case 'aiStudentSuccess':
                return <AIStudentSuccessPredictor />;
            case 'aiDecisionSupport':
                return <AIDecisionSupportSystem />;
            case 'aiReportSummarizer':
                return <AIReportSummarizer />;
            case 'aiBudgetOptimizer':
                return <AIBudgetOptimizer />;
            default:
                // Handle missing components with placeholders
                if (activeView !== 'dashboard') {
                    return <PlaceholderContent title={activeView.replace(/([A-Z])/g, ' $1').trim()} message="This feature is under development." />;
                }
                return (
                     <div className="space-y-6">
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                            <StatCard title="Total Students" value="1,250" icon="fa-solid fa-users" color="bg-blue-500" />
                            <StatCard title="Institution Attendance" value="91%" icon="fa-solid fa-user-check" color="bg-green-500" />
                            <StatCard title="Pass Percentage" value="94%" icon="fa-solid fa-award" color="bg-yellow-500" />
                            <StatCard title="Total Staff" value="110" icon="fa-solid fa-users-cog" color="bg-purple-500" />
                        </div>
                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                           <Card title="Overall Attendance Summary" icon="fa-solid fa-chart-bar">
                                <ResponsiveContainer width="100%" height={300}>
                                    <BarChart data={ATTENDANCE_DATA}>
                                        <CartesianGrid strokeDasharray="3 3" />
                                        <XAxis dataKey="name" />
                                        <YAxis />
                                        <Tooltip />
                                        <Legend />
                                        <Bar dataKey="percentage" fill="#4f46e5" />
                                    </BarChart>
                                </ResponsiveContainer>
                            </Card>
                            <Card title="AI Highlights" icon="fa-solid fa-star">
                                <div className="bg-orange-50 border-l-4 border-orange-500 text-orange-800 p-4 rounded-md mb-4">
                                    <p><i className="fa-solid fa-arrow-down-short-wide mr-2"></i>The Engineering department has a 12% lower pass rate compared to other departments this semester.</p>
                                </div>
                                <div className="bg-teal-50 border-l-4 border-teal-500 text-teal-800 p-4 rounded-md">
                                    <p><i className="fa-solid fa-money-bill-trend-up mr-2"></i>Fee collection is up by 7% compared to the last quarter. Highest in the Commerce department.</p>
                                </div>
                            </Card>
                        </div>
                    </div>
                );
        }
    };

    return (
        <DashboardLayout
            userRole={UserRole.MANAGEMENT}
            menuItems={MANAGEMENT_MENU}
            activeView={activeView}
            setActiveView={setActiveView}
            onLogout={handleLogout}
        >
            {renderContent()}
        </DashboardLayout>
    );
};

export default ManagementDashboard;